set(_CATKIN_CURRENT_PACKAGE "navigation_launch")
set(navigation_launch_VERSION "0.0.0")
set(navigation_launch_MAINTAINER "bender <bender@todo.todo>")
set(navigation_launch_PACKAGE_FORMAT "2")
set(navigation_launch_BUILD_DEPENDS "rospy" "std_msgs")
set(navigation_launch_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(navigation_launch_BUILDTOOL_DEPENDS "catkin")
set(navigation_launch_BUILDTOOL_EXPORT_DEPENDS )
set(navigation_launch_EXEC_DEPENDS "rospy" "std_msgs")
set(navigation_launch_RUN_DEPENDS "rospy" "std_msgs")
set(navigation_launch_TEST_DEPENDS )
set(navigation_launch_DOC_DEPENDS )
set(navigation_launch_URL_WEBSITE "")
set(navigation_launch_URL_BUGTRACKER "")
set(navigation_launch_URL_REPOSITORY "")
set(navigation_launch_DEPRECATED "")